SELECT *
FROM {{ ref('all_score_99') }}
WHERE Player LIKE '%Neres%' 
  OR Player LIKE '%Lukaku%' 
  OR Player LIKE '%Politano%'
  OR Player LIKE '%McTominay%'
  OR Player LIKE '%Lobotka%'
  OR Player LIKE '%Anguissa%'
  OR Player LIKE '%Oliviera%'
  OR Player LIKE '%Buongiorno%'
  OR Player LIKE '%Amir Rrahmani%'
  OR Player LIKE '%Giovanni Di Lorenzo%'
  OR Player LIKE '%Alex Meret%'
  OR Player LIKE '%Lautaro Martínez%'
  OR Player LIKE '%Marcus Thuram%'
  OR Player LIKE '%Henrikh Mkhitaryan%'
  OR Player LIKE '%Hakan Çalhanoğlu%' 
  OR Player LIKE '%Nicolò Barella%' 
  OR Player LIKE '%Denzel Dumfries%'
  OR Player LIKE '%Alessandro Bastoni%' 
  OR Player LIKE '%Francesco Acerbi%'
  OR Player LIKE '%Benjamin Pavard%'
  OR Player LIKE '%Yann Sommer%'
  OR Player LIKE '%Mateo Retegui%'
  OR Player LIKE '%Ademola Lookman%'
  OR Player LIKE '%Charles De Ketelaere%'
  OR Player LIKE '%Davide Zappacosta%'
  OR Player LIKE '%Éderson%'
  OR Player LIKE '%Marten de Roon%'
  OR Player LIKE '%Raoul Bellanova%'
  OR Player LIKE '%Sead Kolašinac%'
  OR Player LIKE '%Isak Hien%'
  OR Player LIKE '%Odilon Kossounou%'
  OR Player LIKE '%Marco Carnesecchi%'
  OR Player LIKE '%Butez%'
  OR Player LIKE '%Douvikas%'
  OR Player LIKE '%Diao%'
  OR Player LIKE '%Ikone%'
  OR Player LIKE '%Nicolás Paz%'
  OR Player LIKE '%Maxence Caqueret%'
  OR Player LIKE '%Máximo Perrone%'
  OR Player LIKE '%Álex Valle%'
  OR Player LIKE '%Alberto Dossena%'
  OR Player LIKE '%Yannik Engelhardt%'
  OR Player LIKE '%Ignace Van Der Brempt%' 