# schema.yml
version: 2

sources:
  - name: div
    schema: League_1
    tables:
      - name: premier_league
        identifier: stats_joueurs_premier_league
      - name: liga
        identifier: stats_joueurs_liga
      - name: bundesliga
        identifier: stats_joueurs_bundesliga
      - name: serie_a
        identifier: stats_joueurs_serie_a
      - name: serie_b
        identifier: stats_joueurs_serie_b
      - name: ligue_1
        identifier: stats_joueurs_ligue1
      - name: eredivisie
        identifier: stats_joueurs_eredivisie
      - name: primeira_liga
        identifier: stats_joueurs_primeira_liga
      - name: belgian_pro_league
        identifier: stats_joueurs_belgian_pro_league
      - name: valeurs_joueurs
        identifier: valeurs_joueurs
      - name: uefa_youth_league_2024
        identifier: uefa_youth_league_2024
      - name: w_bundesliga
        identifier: salaires_bundesliga
      - name: w_liga
        identifier: salaires_liga
      - name: w_ligue1
        identifier: salaires_ligue_1
      - name: w_premeira_liga
        identifier: salaires_premeira_liga
      - name: w_premier_league
        identifier: salaires_premier_league
      - name: w_serie_a
        identifier: salaires_serie_a
      - name: w_serie_b
        identifier: salaires_serie_b
      - name: w_belgian_pro_league
        identifier: salaries_belgian_pro_league
      - name: w_eredivisie
        identifier: salaires_eredivisie
      - name: eredivisie_ado_den_haag
        identifier: eredivisie_ado_den_haag
      - name: eredivisie_afcajax
        identifier: eredivisie_afcajax
      - name: eredivisie_az-alkmaar
        identifier: eredivisie_az-alkmaar
      - name: eredivisie_fc-emmen
        identifier: eredivisie_fc-emmen
      - name: eredivisie_fc-twente
        identifier: eredivisie_fc-twente
      - name: eredivisie_fc-utrecht
        identifier: eredivisie_fc-utrecht
      - name: eredivisie_feyenoord-rotterdam
        identifier: eredivisie_feyenoord-rotterdam
      - name: eredivisie_fortuna-sittard
        identifier: eredivisie_fortuna-sittard
      - name: eredivisie_heracles-almelo
        identifier: eredivisie_heracles-almelo
      - name: eredivisie_pec-zwolle
        identifier: eredivisie_pec-zwolle
      - name: eredivisie_psv-eindhoven
        identifier: eredivisie_psv-eindhoven
      - name: eredivisie_rkc-waalwijk
        identifier: eredivisie_rkc-waalwijk
      - name: eredivisie_sc-heerenveen
        identifier: eredivisie_sc-heerenveen
      - name: eredivisie_vitesse
        identifier: eredivisie_vitesse
      - name: eredivisie_vvv-venlo
        identifier: eredivisie_vvv-venlo
      - name: eredivisie_willem-ii
        identifier: eredivisie_willem-ii
      - name: gk_premier_league
        identifier: gk_premier_league
      - name: gk_bundesliga
        identifier: gk_bundesliga
      - name: gk_eredivisie
        identifier: gk_eredivisie
      - name: gk_serie_a
        identifier: gk_serie_a
      - name: gk_serie_b
        identifier: gk_serie_b
      - name: gk_ligue_1
        identifier: gk_ligue_1
      - name: gk_liga
        identifier: gk_liga
      - name: gk_belgian_pro_league
        identifier: gk_belgian_pro_league
      - name: gk_primeira
        identifier: gk_primeira
      - name: laliga_valeurs
        identifier: laliga_valeurs
      - name: seriea_players_market_values2
        identifier: seriea_players_market_values2
      - name: leicester_2015_2016_stats
        identifier: leicester_2015_2016_stats