{% macro cast_all(schema_name, table_name) %}
SELECT
  League,
  SAFE_CAST(Match_Date AS DATE) AS Match_Date,
  SAFE_CAST(REGEXP_EXTRACT(Matchweek, r'Matchweek\s+(\d+)') AS INT64) AS Matchweek,
  Team,
  Home_Away,
  Player,
  SAFE_CAST(Player_Num AS INT64) AS Player_Num,
  Nation,
  Pos,
  SAFE_CAST(REGEXP_EXTRACT(Age, r'^\d{2}') AS INT64) AS Age,
  SAFE_CAST(`Min` AS INT64) AS Min,
  SAFE_CAST(Gls AS INT64) AS Gls,
  SAFE_CAST(Ast AS INT64) AS Ast,
  SAFE_CAST(PK AS INT64) AS PK,
  SAFE_CAST(PKatt AS INT64) AS PKatt,
  SAFE_CAST(Sh AS INT64) AS Sh,
  SAFE_CAST(SoT AS INT64) AS SoT,
  SAFE_CAST(CrdY AS INT64) AS CrdY,
  SAFE_CAST(CrdR AS INT64) AS CrdR,
  SAFE_CAST(Touches AS INT64) AS Touches,
  SAFE_CAST(Tkl AS INT64) AS Tkl,
  SAFE_CAST(`Int` AS INT64) AS Int,
  SAFE_CAST(Blocks AS INT64) AS Blocks,
  SAFE_CAST(xG_Expected AS FLOAT64) AS xG_Expected,
  SAFE_CAST(npxG_Expected AS FLOAT64) AS npxG_Expected,
  SAFE_CAST(xAG_Expected AS FLOAT64) AS xAG_Expected,
  SAFE_CAST(SCA_SCA AS INT64) AS SCA_SCA,
  SAFE_CAST(GCA_SCA AS INT64) AS GCA_SCA,
  SAFE_CAST(Cmp_Passes AS INT64) AS Cmp_Passes,
  SAFE_CAST(Att_Passes AS INT64) AS Att_Passes,
  SAFE_CAST(Cmp_percent_Passes AS FLOAT64) AS Cmp_percent_Passes,
  SAFE_CAST(PrgP_Passes AS INT64) AS PrgP_Passes,
  SAFE_CAST(Carries_Carries AS INT64) AS Carries_Carries,
  SAFE_CAST(Att_Take_Ons AS INT64) AS Att_Take_Ons,
  SAFE_CAST(Succ_Take_Ons AS INT64) AS Succ_Take_Ons
FROM {{ source(schema_name, table_name) }}
{% endmacro %}